# Generated by Django 5.0.6 on 2026-02-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waqi_stations',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.IntegerField()),
                ('iaqi', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('waqi_time', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='aqi.station')),
            ],
            options={
                'db_table': 'waqi_readings',
                'indexes': [models.Index(fields=['created_at'], name='waqi_readin_created_8c078b_idx'), models.Index(fields=['station', 'created_at'], name='waqi_readin_station_58b876_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_iso', models.CharField(blank=True, max_length=64, null=True)),
                ('temp_c', models.FloatField(null=True)),
                ('pressure_msl_hpa', models.FloatField(null=True)),
                ('surface_pressure_hpa', models.FloatField(null=True)),
                ('cloudcover_pct', models.FloatField(null=True)),
                ('visibility_m', models.FloatField(null=True)),
                ('weather_code', models.IntegerField(null=True)),
                ('precipitation_mm', models.FloatField(null=True)),
                ('windspeed_10m_ms', models.FloatField(null=True)),
                ('soil_temperature_6cm_c', models.FloatField(null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_readings', to='aqi.station')),
            ],
            options={
                'db_table': 'waqi_temp_readings',
                'indexes': [models.Index(fields=['created_at'], name='waqi_temp_r_created_2b6310_idx'), models.Index(fields=['station', 'created_at'], name='waqi_temp_r_station_238437_idx'), models.Index(fields=['observed_iso'], name='waqi_temp_r_observe_eb2070_idx')],
                'unique_together': {('station', 'observed_iso')},
            },
        ),
    ]
